### PR TITLE
New version swirl course "A (very) short introduction to R"

### PR DESCRIPTION
**Pull request by ClaudiaBrauer**
I fixed some errors in the previous version.

### CODE REVIEW

**Comment by seankross** [comment]
Thanks!

**Comment by WilCrofter** [comment]
Every so often I just can't help sending kudos. Brilliant job, you all!

**Comment by seankross** [comment]
Hi @WilCrofter hope you're doing well!

**Comment by WilCrofter** [comment]
Hey, @seankross. All is well here, thanks. Hope the same is true in sunny San Diego. Currently standing up a 3-node openstack cloud at home, working on math (the Landau problems in number theory) and, with neuroscience friends at JHMI and elsewhere, have submitted a manuscript to PNAS.

**Comment by ClaudiaBrauer** [comment]
Dear Sean,


?Thanks for the quick update!


By the way, there is no way I can see how often the course has been installed or downloaded, right?


Claudia


________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University and Research

________________________________
Van: Sean Kross <notifications@github.com>
Verzonden: dinsdag 2 april 2019 18:45
Aan: swirldev/scn
CC: Brauer, Claudia; Author
Onderwerp: Re: [swirldev/scn] New version swirl course "A (very) short introduction to R" (#10)


Thanks!

-

**Comment by seankross** [comment]
Hi @ClaudiaBrauer,

Unfortunately I don't have any way of tracking course installations, sorry.

Sean

**Comment by ClaudiaBrauer** [comment]
?I thought as much. Thanks anyway!


Claudia


________________________________
C.C. Brauer, PhD., lecturer-researcher
Hydrology and Quantitative Water Management Group, Wageningen University and Research

________________________________
Van: Sean Kross <notifications@github.com>
Verzonden: woensdag 3 april 2019 21:55
Aan: swirldev/scn
CC: Brauer, Claudia; Mention
Onderwerp: Re: [swirldev/scn] New version swirl course "A (very) short introduction to R" (#10)


Hi @ClaudiaBrauer<https://github.com/ClaudiaBrauer>,

Unfortunately I don't have any way of tracking course installations, sorry.

Sean

-

**Pull request merged**
