### PR TITLE
Add several courses in german to SCN

### PR DESCRIPTION
**Pull request by nielsgeo**
Dear team swirl,
colleagues and me created several swirl courses with sample data and problems from various earth science disciplines. We contributed the first course earlier this year. I added the remaining ones to share on SCN. See .rmd / .html files for details on course contents. Most of the courses are in german to ease german R beginners getting started with R. Hope that everything is ready to merge, please let me know if we can improve anything.

### CODE REVIEW

**Comment by seankross** [comment]
Looks good to me and thank you so much for the contribution. Please double check this content on https://swirlstats.com/scn/ once this PR has been merged.

**Comment by nielsgeo** [comment]
Checked https://swirlstats.com/scn/ and installing courses from the repo. Looks fine and works well. Thanks for the quick merge, Sean Kross!

**Comment by fabian-s** [comment]
@nielsgeo  

I've been using these swirl courses for my intro stats class this semester, thanks so much for providing them. 
My students did stumbled over some bugs in them, though, e.g.:

image
(windows() only works in Windows.....)

image


I'd like to try to patch those they found to give something back -- **where can I find the raw YAML etc files for your courses?**
Are they forkable on Github somewhere?

**Comment by nielsgeo** [comment]
@fabian-s 
To unpack a .swc-file you can use swirlify's unpack_course(). You'll get yaml files and other elements of the course.
We did a lot of testing before sending the pull request, but time and ressources were limited... Most likely there's still a lot to fix. Looking forward to the patched version!

**Pull request merged**
