### PR TITLE
GHA: Automated transfer of swc files from DataTrail

### PR DESCRIPTION
**Pull request by cansavvy**
### Description:
 This PR was initiated by transfer-rendered.yml the DataTrail swirl repository.
 It copies over the swc files from the https://github.com/datatrail-jhu/datatrail-swirl
 to run properly.

### CODE REVIEW

**Comment by cansavvy** [comment]
Made some updates to some of the questions based on a review from @allissadillman

**Comment by seankross** [comment]
Is there anything to actually review here? Are you ready for me to merge this?

**Comment by cansavvy** [comment]
> Is there anything to actually review here? Are you ready for me to merge this?

There’s not much to review, just on principle didn’t want to merge without you knowing.

**Comment by seankross** [comment]
Thanks Candace.

**Pull request merged**
